---
# handlers file for prometheus

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted

- name: Restart Blackbox Exporter
  systemd:
    name: blackbox_exporter
    state: restarted
