{
 "title": "Hp ilo",
 "time": { "to": "now", "from": "now-5m" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ILO",
   "type": "stat",
   "gridPos": { "y": 0, "h": 7, "w": 24, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hpilo_firmware_version{job=\"hpilo openstack\"}",
     "legendFormat": "{{ilo_host}}"
    }
   ]
  },
  {
   "title": "Hardware error in Tabriz",
   "type": "gauge",
   "gridPos": { "y": 7, "h": 8, "w": 24, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((hpilo_storage{job=\"hpilo openstack\"}) and  (hpilo_fans{job=\"hpilo openstack\"}) and (hpilo_memory{job=\"hpilo openstack\"}) and (hpilo_power_supplies{job=\"hpilo openstack\"}) and (hpilo_processor{job=\"hpilo openstack\"}) and (hpilo_temperature{job=\"hpilo openstack\"})) ",
     "legendFormat": "{{ilo_host}} "
    }
   ]
  },
  {
   "title": "hpilo fans",
   "type": "gauge",
   "gridPos": { "y": 15, "h": 8, "w": 12, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hpilo_fans{job=\"hpilo openstack\"}",
     "legendFormat": "{{ilo_host}} "
    }
   ]
  },
  {
   "title": "hpilo_bios_hardware",
   "type": "gauge",
   "gridPos": { "y": 15, "h": 8, "w": 12, "x": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hpilo_bios_hardware{job=\"hpilo openstack\"}",
     "legendFormat": "{{ilo_host}} "
    }
   ]
  },
  {
   "title": "hpilo processor",
   "type": "gauge",
   "gridPos": { "y": 23, "h": 8, "w": 12, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hpilo_processor{job=\"hpilo openstack\"}",
     "legendFormat": "{{ilo_host}} "
    }
   ]
  },
  {
   "title": "hpilo_power_supplies",
   "type": "gauge",
   "gridPos": { "y": 23, "h": 8, "w": 12, "x": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hpilo_power_supplies{job=\"hpilo openstack\"}",
     "legendFormat": "{{ilo_host}} "
    }
   ]
  },
  {
   "title": "hpilo_storage",
   "type": "gauge",
   "gridPos": { "y": 31, "h": 9, "w": 12, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hpilo_storage{job=\"hpilo openstack\"}",
     "legendFormat": "{{ilo_host}}"
    }
   ]
  },
  {
   "title": "hpilo_memory",
   "type": "gauge",
   "gridPos": { "y": 31, "h": 8, "w": 12, "x": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hpilo_memory{job=\"hpilo openstack\"}",
     "legendFormat": "{{ilo_host}} "
    }
   ]
  }
 ]
}