{
 "title": "Cisco switch",
 "description": "For snmp_exporter IF-MIB",
 "tags": [
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ifHCInOctets{job=\"snmp_switch\"}, instance)"
    }
   },
   {
    "name": "ifAlias",
    "query": {
     "query": "label_values(ifHCInOctets{job=\"snmp_switch\",instance=\"$Instance\"}, ifAlias)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m.15m,30m,45m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Status",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"snmp_switch\",instance=~\".*greenweb.local|.*iranserver.local\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Switch Uptime",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sysUpTime{job='snmp_switch'}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "PING TimeLine",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"networkping\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\"}/(ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\"}+ciscoMemoryPoolFree{ciscoMemoryPoolType=\"1\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpmCPUTotal1minRev{job=\"snmp_switch\"}",
     "legendFormat": "{{instance}} {{cpmCPUTotalIndex}}"
    }
   ]
  },
  {
   "title": "Switch Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciscoEnvMonTemperatureStatusValue{ciscoEnvMonTemperatureStatusIndex=\"1\",job=\"snmp_switch\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage Graph",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpmCPUTotal1minRev{job=\"snmp_switch\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "HIGHEST OUT USAGE All Switch",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"snmp_switch\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "HIGHEST OUT USAGE For Switch : $Instance",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"snmp_switch\",instance=\"$Instance\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "HIGHEST IN USAGE  All Switch",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"snmp_switch\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Max In (Current) Switch : $Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\",instance=\"$Instance\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current) Switch : $Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\",instance=\"$Instance\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "HIGHEST IN USAGE For Switch : $Instance",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"snmp_switch\",instance=\"$Instance\"}[$interval])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Max In (Current) Port: $ifAlias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\",instance=\"$Instance\",ifAlias=\"$ifAlias\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Avg In  $ifAlias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((rate(ifHCInOctets{job=\"$Job\",instance=\"$Instance\",ifAlias=\"$ifAlias\", ifHighSpeed=~\"1000|10000\"}[5m]) )[30d:])"
    }
   ]
  },
  {
   "title": "Max Out (Current) Port: $ifAlias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\",instance=\"$Instance\",ifAlias=\"$ifAlias\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In  Switch : $Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\",instance=\"$Instance\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out Switch : $Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\",instance=\"$Instance\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Avg Out $ifAlias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((rate(ifHCOutOctets{job=\"$Job\",instance=\"$Instance\",ifAlias=\"$ifAlias\", ifHighSpeed=~\"1000|10000\"}[5m]) )[30d:])"
    }
   ]
  },
  {
   "title": "Total In  Port: $ifAlias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\",instance=\"$Instance\",ifAlias=\"$ifAlias\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out Port: $ifAlias",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\",instance=\"$Instance\",ifAlias=\"$ifAlias\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Out (Current)  For Switch : $Instance",
   "type": "graph",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\",instance=\"$Instance\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)  For Switch : $Instance",
   "type": "graph",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\",instance=\"$Instance\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In  For Switch : $Instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\",instance=\"$Instance\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "- irate(ifHCInOctets{job=\"$Job\",instance=\"$Instance\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Power Supply Fan Status Of Switches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciscoEnvMonFanState{job=\"snmp_switch\",ciscoEnvMonFanStatusIndex!=\"1\"}",
     "legendFormat": "{{ciscoEnvMonFanStatusIndex}} {{instance}}  "
    }
   ]
  },
  {
   "title": "Power Supply Status Of Switches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciscoEnvMonSupplyState{job=\"snmp_switch\"}",
     "legendFormat": "{{ciscoEnvMonSupplyStatusIndex}} {{instance}}  "
    }
   ]
  }
 ]
}