{
 "title": "tabriz switch",
 "description": "For snmp_exporter IF-MIB",
 "tags": [
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "to": "now", "from": "now-30m" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": "label_values(ifHCInOctets,  job)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "y": 0, "h": 7, "w": 24, "x": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "singlestat",
   "gridPos": { "y": 7, "h": 3, "w": 6, "x": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "singlestat",
   "gridPos": { "y": 7, "h": 3, "w": 6, "x": 6 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "singlestat",
   "gridPos": { "y": 7, "h": 3, "w": 6, "x": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "singlestat",
   "gridPos": { "y": 7, "h": 3, "w": 6, "x": 18 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "graph",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "y": 10, "h": 9, "w": 12, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "graph",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "y": 10, "h": 9, "w": 12, "x": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "y": 19, "h": 10, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}