{
 "title": "Keepalived Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(keepalived_up, node_name)"
   }
  ]
 },
 "panels": [
  { "title": "Keepalived Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VRRP State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{node_name=\"$node\"}",
     "legendFormat": "{{ iname }} - {{ ip_address }}"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_up{node_name=\"$node\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Release Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_release_master_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Become Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_become_master_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Advertisements Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_advertisements_received_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Advertisements Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_advertisements_sent_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Priority Zero Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_priority_zero_received_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Priority Zero Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_priority_zero_sent_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Packet Length Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_packet_length_errors_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Advertisement Interval Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_advertisements_interval_errors_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "TTL Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_ip_ttl_errors_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Address List Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_address_list_errors_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Invalid Type Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_invalid_type_received_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Gratuitous ARP Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_gratuitous_arp_delay_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Authentication Invalid",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_authentication_invalid_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Authentication Mismatch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_authentication_mismatch_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Authentication Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(keepalived_authentication_failure_total{node_name=\"$node\"}[1m])",
     "legendFormat": "{{ iname }}"
    }
   ]
  }
 ]
}