{
 "title": "SNMP Stats tbz",
 "description": "For snmp_exporter IF-MIB",
 "time": { "from": "2021-01-03T07:25:56.277Z", "to": "2021-01-03T07:35:56.277Z" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": "label_values(ifHCInOctets,  job)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "In (Current)",
   "type": "graph",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "PhysAddress",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "ifPhysAddress" }
   ]
  }
 ]
}