{
 "title": "tabriz switch",
 "description": "For snmp_exporter IF-MIB",
 "tags": [
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": "label_values(ifHCInOctets,  job)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{job=\"$Job\"} * 10",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}