---
- name: Check if Blackbox Exporter service is installed
  systemd:
    name: blackbox_exporter
  register: blackbox_exporter_service
  ignore_errors: yes
  tags:
    - blackbox_exporter

- name: Download the Blackbox Exporter script
  get_url:
    url: "https://raw.githubusercontent.com/greenweb-cloud/prometheus_exporters/main/blackbox_exporter/blackbox-exporter.sh"
    dest: "/tmp/blackbox-exporter.sh"
    mode: '0755'
  when: blackbox_exporter_service.status != 'active'
  tags:
    - blackbox_exporter

- name: Run the Blackbox Exporter script
  shell: "/tmp/blackbox-exporter.sh"
  when: blackbox_exporter_service.status != 'active'
  tags:
    - blackbox_exporter

- name: Remove the Blackbox Exporter script
  file:
    path: "/tmp/blackbox-exporter.sh"
    state: absent
  when: blackbox_exporter_service.status != 'active'
  tags:
    - blackbox_exporter

- name: Create the directory for Blackbox Exporter configuration
  file:
    path: /etc/blackbox_exporter
    state: directory
    mode: '0755'
  tags:
    - blackbox_exporter

- name: Download Blackbox Exporter configuration
  get_url:
    url: "https://raw.githubusercontent.com/greenweb-cloud/prometheus_exporters/main/blackbox_exporter/blackbox.yml"
    dest: "/etc/blackbox_exporter/blackbox.yml"
    mode: '0644'
  when: blackbox_exporter_service.status != 'active'
  tags:
    - blackbox_exporter
  notify: Restart Blackbox Exporter
