---
# tasks file for prometheus
#
- name: scp config_monitoring to computs
  copy:
    src: "{{ exporter }}"
    dest: "{{ exporter_pass }}"
    mode: 0755
  tags:
    - compute
    

- name: run script for install node_exporter
  shell: "{{ run_command }}"
  tags:
    - compute
    

