---
# tasks file for prometheus
#
- name: scp config_monitoring to computs
  copy:
    src: "{{ source_node_exporter }}"
    dest: "{{ dest_path  }}"
    mode: 0755
  tags:
    - compute
    
- name: run script for install node_exporter
  shell: "{{ run_node_exporter }}"
  tags:
    - compute
    
- name: Configure node_exporter compute for prometheus
  template:
    src: compute.j2
    dest: /etc/prometheus/compute.json
    mode: 0755
  tags:
    - monitor_compute

- name: restart node_exporter
  shell: "systemctl restart node_exporter"
  tags:
    - compute

- name: reload prometheus
  shell: "systemctl reload prometheus"
  tags:
    - monitor_compute
