---
# tasks file for prometheus
#
- name: scp config_monitoring to glance
  copy:
    src: "{{ source_node_exporter  }}"
    dest: "{{ dest_path }}"
    mode: 0755
  tags:
    - glance
    

- name: run script for install node_exporter
  shell: "{{ run_node_exporter }}"
  tags:
    - glance
    
- name: Configure node_exporter glance for prometheus
  template:
    src: glance.j2
    dest: /etc/prometheus/glance.json
    mode: 0755
  tags:
    - monitor_glance

- name: restart node_exporter
  shell: "systemctl restart node_exporter"
  tags:
    - glance

- name: restart prometheus
  shell: "systemctl restart prometheus"
  tags:
    - monitor_glance
