---
#tasks file for haproxy exporter


- name: scp config_monitoring haproxy exporter
  copy:
    src: "{{ source_haproxy_exporter }}"
    dest: "{{ dest_path }}"
    mode: 0755
#  when: not haproxy_status.stat.exists
  tags:
    - haproxy
   

- name: run script for install haproxy exporter
  shell: "{{ run_haproxy_exporter  }}"
  tags:
    - haproxy
    
- name: Copy haproxy_exporter target switch for prometheus
  template:
    src: haproxy.j2
    dest: "{{template_path}}haproxy.json"
    mode: 0755
  tags:
    - haproxy_config


- name: restart haproxy_exporter
  shell: "systemctl restart haproxy_exporter"
  tags:
    - haproxy

- name: restart prometheus
  shell: "systemctl restart prometheus"
  tags:
    - haproxy_config
