---
# tasks file for prometheus
#
- name: scp config_monitoring to infra
  copy:
    src: "{{ exporter }}"
    dest: "{{ exporter_pass }}"
    mode: 0755
  tags:
    - infra
    

- name: run script for install node_exporter
  shell: "{{ run_command }}"
  tags:
    - infra
    
- name: Configure node_exporter infra for prometheus
  template:
    src: infra.j2
    dest: /etc/prometheus/infra.json
    mode: 0755
  tags:
    - monitor_infra
- name: restart prometheus
  shell: "systemctl restart prometheus"
  tags:
    - monitor_infra
