---
# tasks file for prometheus
#
- name: copy script node exporter to destinition host
  when: inventory_hostname in groups['testGroup']
  copy:
    src: "{{ source_node_exporter }}"
    dest: "{{ dest_path  }}"
    mode: 0755
  tags:
    - node_exporter
    
- name: run script for install node exporter
  when: inventory_hostname in groups['testGroup']
  shell: "{{ run_node_exporter }}"
  tags:
    - node_exporter
    
- name: generate node exporter for prometheus
  when: inventory_hostname in groups['monitoring']  
  template:
    src: node_exporter.j2
    dest: /etc/prometheus/exporter/node_exporter.json
    mode: 0755
  tags:
    - node_exporter

- name: restart node_exporter
  when: inventory_hostname in groups['testGroup']
  shell: "systemctl restart node_exporter"
  tags:
    - node_exporter

