---

- name: generate snmp config
  template:
    src: snmp.j2
    dest: "{{dest_config_path}}service_snmp_exporter.json"
    mode: 0755
  tags:
    - snmp_consul

- name: generate blckbox config
  template:
    src: blackbox.j2
    dest: "{{dest_config_path}}service_blackbox_exporter.json"
    mode: 0755
  tags:
    - blackbox_consul
