---
- hosts: "{{ machine }}"
  tasks:

    - name: deploy backup service
      import_role:
        name: prometheus

    - name: deploy alert manager service
      import_role:
        name: alertmanager
