---
- hosts: "{{ machine }}"
  tasks:
    - name: deploy prometheus service
      import_role:
        name: prometheus
        
    - name: deploy alert manager service
      import_role:
        name: alertmanager

    - name: deploy grafana service
      import_role:
        name: grafana

    - name: deploy consul service
      import_role:
        name: consul

