---
# defaults file for prometheus
#exporter: "/opt/prometheus_exporters/ansible/prometheus/files/exporter"
#exporter: "/opt/prometheus_exporters/node_exporter/node-exporter.sh"
exporter: "../files/node-exporter.sh"
exporter_pass: "/home/"
run_command: "/home/node-exporter.sh"
