---
# defaults file for prometheus
#exporter: "/opt/prometheus_exporters/ansible/prometheus/files/exporter"
#exporter: "/opt/prometheus_exporters/node_exporter/node-exporter.sh"
exporter: "../files/node-exporter.sh"
exporter_pass: "/home/"
run_command: "/home/node-exporter.sh"
compute_ip:
  - "compute1.iranserver.com:9100"
  - "compute2.iranserver.com:9100"
  - "compute3.iranserver.com:9100"
  - "compute4.iranserver.com:9100"
  - "compute5.iranserver.com:9100"
  - "compute6.iranserver.com:9100"
  - "compute7.iranserver.com:9100"
  - "compute8.iranserver.com:9100"
  - "compute9.iranserver.com:9100"
  - "compute10.iranserver.com:9100"
  - "compute11.iranserver.com:9100"
  - "compute12.iranserver.com:9100"
  - "compute13.iranserver.com:9100"
  - "compute14.iranserver.com:9100"
  - "compute15.iranserver.com:9100"
  - "compute16.iranserver.com:9100"
  - "compute17.iranserver.com:9100"
  - "compute18.iranserver.com:9100"
  - "compute19.iranserver.com:9100"
  - "compute20.iranserver.com:9100"
  - "compute21.iranserver.com:9100"
  - "compute22.iranserver.com:9100"
  - "compute23.iranserver.com:9100"
  - "compute24.iranserver.com:9100"
  - "compute25.iranserver.com:9100"

infra_ip:
  - "infra1.iranserver.com:9100"
  - "infra2.iranserver.com:9100"
  - "infra3.iranserver.com:9100"
nfs_ip:
  - "nfs.iranserver.com:9100"

glance_ip:
  - "glance1.iranserver.com:9100"
  - "glance2.iranserver.com:9100"
  - "glance3.iranserver.com:9100"



